/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}"
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#0b0f12",
        "on-primary-fixed": "#031312",
        "on-secondary-fixed": "#1f1604",
        "error-dim": "#d7383b",
        "tertiary": "#e3a72f",
        "surface-container-low": "#10161a",
        "on-tertiary": "#251703",
        "on-error": "#490006",
        "surface": "#0b0f12",
        "surface-variant": "#263137",
        "secondary": "#d6a642",
        "secondary-fixed": "#f2d287",
        "on-secondary-fixed-variant": "#5b3d04",
        "surface-tint": "#6ee7d8",
        "inverse-surface": "#f3f7f6",
        "secondary-container": "#674708",
        "tertiary-dim": "#e3a72f",
        "primary-dim": "#48c7bd",
        "tertiary-fixed-dim": "#e9b95d",
        "primary": "#6ee7d8",
        "on-error-container": "#ffa8a3",
        "on-primary-container": "#064b47",
        "tertiary-container": "#7a5106",
        "primary-fixed": "#6ee7d8",
        "primary-container": "#174f4b",
        "on-primary-fixed-variant": "#09615b",
        "error-container": "#9f0519",
        "surface-container": "#151d21",
        "secondary-fixed-dim": "#ddb85d",
        "on-surface": "#f3f7f6",
        "surface-container-highest": "#263137",
        "on-secondary-container": "#fff6dd",
        "on-secondary": "#2d1e02",
        "primary-fixed-dim": "#48c7bd",
        "surface-dim": "#0b0f12",
        "on-tertiary-container": "#fff4d6",
        "on-tertiary-fixed-variant": "#6e4804",
        "on-surface-variant": "#a5b2b6",
        "inverse-on-surface": "#405056",
        "surface-container-lowest": "#080b0d",
        "surface-container-high": "#1b252a",
        "on-background": "#f3f7f6",
        "on-primary": "#031312",
        "inverse-primary": "#11746c",
        "surface-bright": "#303d43",
        "error": "#ff716c",
        "on-tertiary-fixed": "#281900",
        "outline-variant": "#3b484e",
        "outline": "#7f8e93",
        "tertiary-fixed": "#f0c978",
        "secondary-dim": "#b9841a"
      },
      fontFamily: {
        "headline": ["Geist", "Space Grotesk", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Geist", "Space Grotesk", "sans-serif"],
        "mono": ["JetBrains Mono", "SFMono-Regular", "ui-monospace", "monospace"]
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
