/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}"
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#f5f5f7",
        "on-primary-fixed": "#ffffff",
        "on-secondary-fixed": "#1d1d1f",
        "error-dim": "#d70015",
        "tertiary": "#ff9f0a",
        "surface-container-low": "#fbfbfd",
        "on-tertiary": "#1d1d1f",
        "on-error": "#ffffff",
        "surface": "#ffffff",
        "surface-variant": "#e8eaed",
        "secondary": "#6e6e73",
        "secondary-fixed": "#f2f2f7",
        "on-secondary-fixed-variant": "#424245",
        "surface-tint": "#0071e3",
        "inverse-surface": "#1d1d1f",
        "secondary-container": "#f2f2f7",
        "tertiary-dim": "#d97904",
        "primary-dim": "#0057b8",
        "tertiary-fixed-dim": "#ffd49a",
        "primary": "#0071e3",
        "on-error-container": "#b00020",
        "on-primary-container": "#003a75",
        "tertiary-container": "#fff2df",
        "primary-fixed": "#0071e3",
        "primary-container": "#e7f1ff",
        "on-primary-fixed-variant": "#004f9f",
        "error-container": "#ffecec",
        "surface-container": "#ffffff",
        "secondary-fixed-dim": "#e5e5ea",
        "on-surface": "#1d1d1f",
        "surface-container-highest": "#e8eaed",
        "on-secondary-container": "#424245",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#0a84ff",
        "surface-dim": "#ececf0",
        "on-tertiary-container": "#5c3600",
        "on-tertiary-fixed-variant": "#805200",
        "on-surface-variant": "#6e6e73",
        "inverse-on-surface": "#f5f5f7",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#f2f2f7",
        "on-background": "#1d1d1f",
        "on-primary": "#ffffff",
        "inverse-primary": "#66b3ff",
        "surface-bright": "#ffffff",
        "error": "#ff3b30",
        "on-tertiary-fixed": "#1d1d1f",
        "outline-variant": "#d2d2d7",
        "outline": "#86868b",
        "tertiary-fixed": "#ffcc80",
        "secondary-dim": "#8e8e93"
      },
      fontFamily: {
        "headline": ["Geist", "Space Grotesk", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Geist", "Space Grotesk", "sans-serif"],
        "mono": ["JetBrains Mono", "SFMono-Regular", "ui-monospace", "monospace"]
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
