/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "./public/index.html"
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#0e0e13",
        "on-primary-fixed": "#003f43",
        "on-secondary-fixed": "#500086",
        "error-dim": "#d7383b",
        "tertiary": "#ff59e3",
        "surface-container-low": "#131319",
        "on-tertiary": "#42003a",
        "on-error": "#490006",
        "surface": "#0e0e13",
        "surface-variant": "#25252d",
        "secondary": "#c47fff",
        "secondary-fixed": "#e7c5ff",
        "on-secondary-fixed-variant": "#7900c6",
        "surface-tint": "#8ff5ff",
        "inverse-surface": "#fcf8ff",
        "secondary-container": "#8c00e5",
        "tertiary-dim": "#ff59e3",
        "primary-dim": "#00deec",
        "tertiary-fixed-dim": "#ff68e3",
        "primary": "#8ff5ff",
        "on-error-container": "#ffa8a3",
        "on-primary-container": "#005359",
        "tertiary-container": "#ff05e5",
        "primary-fixed": "#00eefc",
        "primary-container": "#00eefc",
        "on-primary-fixed-variant": "#005e64",
        "error-container": "#9f0519",
        "surface-container": "#19191f",
        "secondary-fixed-dim": "#ddb3ff",
        "on-surface": "#f9f5fd",
        "surface-container-highest": "#25252d",
        "on-secondary-container": "#fff5ff",
        "on-secondary": "#340059",
        "primary-fixed-dim": "#00deec",
        "surface-dim": "#0e0e13",
        "on-tertiary-container": "#1b0017",
        "on-tertiary-fixed-variant": "#6d0061",
        "on-surface-variant": "#acaab1",
        "inverse-on-surface": "#55545b",
        "surface-container-lowest": "#000000",
        "surface-container-high": "#1f1f26",
        "on-background": "#f9f5fd",
        "on-primary": "#005d63",
        "inverse-primary": "#006a71",
        "surface-bright": "#2c2b33",
        "error": "#ff716c",
        "on-tertiary-fixed": "#33002d",
        "outline-variant": "#48474d",
        "outline": "#76747b",
        "tertiary-fixed": "#ff85e4",
        "secondary-dim": "#a533ff"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Space Grotesk", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
